feat: add controllers
nikolay-977/java-shareit pull request #1
Opened 2022-09-21 15:42 UTC by nikolay-977

2022-09-21 20:47 UTC, Frilock requested changes
Добрый день, в целом все ок, вопросов по работе не много, жду новую итерацию. 
Кроме того, не знаю писал или нет, но советую поставить плагин sonarlint - статический анализатор кода, подсветит возможные ошибки и покажет ряд хороших практик.

2022-09-21 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +            if (user.getEmail().equals(email)) {
А Вы уверены, что email будет заполнен? Вы тут NPE не получите?, вообще чтобы таких вопросов и подозрений не возникало лучше null safe equals использовать - Objects.equals(o1, o2)

2022-09-21 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserDto.java
> +    private String name;
Как то не логично если name будет не заполнено...

2022-09-21 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/User.java
> +    private String name;
Как то не логично, если name будет не заполнено...

2022-09-21 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            owner = UserRowMapper.toUser(userRepository.getById(userId));
Тут можно все в одну строчку сделать, сразу внутри return UserRowMapper.toUser(userRepository.getById(userId));
А поле owner можно убрать

2022-09-21 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        } else return items.stream()
Не делайте блоков без скобок, вы потом когда нибуть ошибку получите из за невнимательности

2022-09-21 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                .filter(i -> i.getDescription().toUpperCase().contains(text.toUpperCase()) && i.getAvailable() && !text.isEmpty())
i.getDescription null не вернет? NPE не получите?

2022-09-21 20:47 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingDto.java
> +    private String status;
А тут набор статусов заранее не известен? Если известен то лучше enam использовать

2022-09-22 16:47 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
> +            if (user.getEmail().equals(email)) {
Поправил

2022-09-22 16:48 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/user/UserDto.java
> +    private String name;
Поправил

2022-09-22 16:48 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/user/User.java
> +    private String name;
Поправил

2022-09-22 16:50 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +            owner = UserRowMapper.toUser(userRepository.getById(userId));
Поправил

2022-09-22 16:51 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        } else return items.stream()
Поправил

2022-09-22 17:02 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                .filter(i -> i.getDescription().toUpperCase().contains(text.toUpperCase()) && i.getAvailable() && !text.isEmpty())
поправил

2022-09-22 17:22 UTC, nikolay-977 commented
> Добрый день, в целом все ок, вопросов по работе не много, жду новую итерацию. Кроме того, не знаю писал или нет, но советую поставить плагин sonarlint - статический анализатор кода, подсветит возможные ошибки и покажет ряд хороших практик.

Добрый день.

Спасибо за ревью.

2022-09-22 19:04 UTC, Frilock approved these changes
Принято, желаю дальнейших успехов

2022-09-23 14:38 UTC, merged