feature: add bookings
nikolay-977/java-shareit pull request #5
Opened 2022-10-18 11:58 UTC by nikolay-977

2022-10-18 20:46 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе. Если что пишите

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Entity
Будьте аккуратны при совместном использовании Data и Builder https://habr.com/ru/company/haulmont/blog/564682/

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "id")
Для Id Column можно не указывать

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @GeneratedValue(strategy = GenerationType.AUTO, generator = "bookings_id_seq")
А почему не @GeneratedValue(strategy = GenerationType.IDENTITY)? Вроде это стандартная практика

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto create(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody BookingDto bookingDto) {
Давайте методы сделаем публичными. Проверьте в других местах

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +@Repository
Аннотацию можно не ставить, если наследуетесь от JpaRepository

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        UserDto bookerDto = UserRowMapper.toUserDto(userRepository.findById(finalUserId).orElseThrow(() -> new NotFoundException(USER_NOT_FOUND_MESSAGE)));
Слишком длинная строка, давайте .orElseThrow(() -> new NotFoundException(USER_NOT_FOUND_MESSAGE)));
С новой строки начнем

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (bookingDto.getStart().isAfter(bookingDto.getEnd())) {
Мне кажется сначала нужно проверить, что bookingDto.getStart() != null, чтобы NPE не получить

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus().equals(newStatus)) {
enum поля правильнее сравнивать через стандартные операторы == и !=, работать будет и так и так, но стандартные операторы банально быстрее

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingState.java
> +    APPROVED, REJECTED, WAITING, CANCELED, ALL, FUTURE, PAST, CURRENT;
двоеточие в конце не нужно

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +    @Column(name = "text", nullable = false)
Для текстовых полей нужно указать размерность, которую вы указали в скриптах

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/comment/CommentDto.java
> +@ToString
По моему ToString входит в Data

2022-10-18 20:46 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getOwner() != null) {
Такие ifы можно заменить на Optional.ofNullable, посмотрите какой там синтаксис (но не принципиально)

2022-10-18 20:46 UTC, Frilock commented on src/main/resources/schema.sql
> +create sequence users_id_seq;
Можно обойтись без sequence  - указал в комментарии выше

2022-10-19 09:30 UTC, nikolay-977 commented
> Добрый день, оставил ряд комментариев к работе. Если что пишите

Добрый день. Спасибо за ревью.

2022-10-19 09:31 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +@Entity
Исправил

2022-10-19 09:31 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @Column(name = "id")
Исправил

2022-10-19 09:31 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @GeneratedValue(strategy = GenerationType.AUTO, generator = "bookings_id_seq")
Исправил

2022-10-19 09:31 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingDto create(@RequestHeader("X-Sharer-User-Id") Long userId, @Valid @RequestBody BookingDto bookingDto) {
Исправил

2022-10-19 09:31 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +@Repository
Исправил

2022-10-19 09:31 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/booking/BookingState.java
> +    APPROVED, REJECTED, WAITING, CANCELED, ALL, FUTURE, PAST, CURRENT;
Исправил

2022-10-19 09:31 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/comment/Comment.java
> +    @Column(name = "text", nullable = false)
Исправил

2022-10-19 09:32 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/comment/CommentDto.java
> +@ToString
Убрал ToString, т.к. в работе не используется

2022-10-19 09:34 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (item.getOwner() != null) {
Спасибо за рекомендацию, с синтаксисом ознакомился. Пока решил оставить как есть.

2022-10-19 09:34 UTC, nikolay-977 commented on src/main/resources/schema.sql
> +create sequence users_id_seq;
Исправил

2022-10-19 16:06 UTC, Frilock approved these changes
Ок, принято. Один комментарий оставил, посмотрите.

2022-10-19 16:06 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/Booking.java
> +    @GeneratedValue(strategy = GenerationType.IDENTITY, generator = "bookings_id_seq")
Это по идее уже не нужно , generator = "bookings_id_seq"

2022-10-20 09:53 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        UserDto bookerDto = UserRowMapper.toUserDto(userRepository.findById(finalUserId).orElseThrow(() -> new NotFoundException(USER_NOT_FOUND_MESSAGE)));
исправил

2022-10-20 09:53 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (booking.getStatus().equals(newStatus)) {
исправил

2022-10-20 09:53 UTC, merged