feature: add item request
nikolay-977/java-shareit pull request #6
Opened 2022-10-22 17:08 UTC by nikolay-977

2022-10-23 19:51 UTC, Frilock requested changes
Добрый вечер, хорошая работа, в целом все хорошо, из мелких комментариев, предлагаю переименовать ваш кастомный класс PageRequest, и в тестовых классах для ряда полей пропустили приватный модификатор

2022-10-23 19:51 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Модификатор

2022-10-23 19:51 UTC, Frilock commented on src/main/java/ru/practicum/shareit/utils/Pagination.java
> +public class Pagination extends PageRequest {
Мне кажется название класса Pagination будет путать, предлагаю назвать ShareltPageRequest, как наследника стандартного PageRequest

2022-10-23 20:04 UTC, nikolay-977 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    ObjectMapper mapper;
Исправил

2022-10-23 20:05 UTC, nikolay-977 commented on src/main/java/ru/practicum/shareit/utils/Pagination.java
> +public class Pagination extends PageRequest {
Исправил

2022-10-24 06:13 UTC, Frilock approved these changes
Принято

2022-10-24 10:43 UTC, merged