feature: add-docker
nikolay-977/java-shareit pull request #7
Opened 2022-10-29 14:25 UTC by nikolay-977

2022-10-31 09:05 UTC, Frilock requested changes
Добрый день, оставил ряд комментариев к работе. Жду новую итерацию.

2022-10-31 09:05 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingController.java
> +@Slf4j
На мой взгляд, данная аннотация лишняя, не вижу использования логгера

2022-10-31 09:05 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/dto/BookingState.java
> +    WAITING;
Лишняя ; в конце. Вам IDEA должна ее сереньким отмечать

2022-10-31 09:05 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/gateway/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
Слишком длинная строка, давайте аргументы будем на новую строчку переносить

2022-10-31 09:05 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/gateway/client/BaseClient.java
> +            if (parameters != null) {
По идее данную конструкцию можно заменить на использование тернарного оператора, будет компактнее

2022-10-31 09:05 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/gateway/client/BaseClient.java
> +        if (response.getStatusCode().is2xxSuccessful()) {
А response.getStatusCode() null не вернет?

2022-10-31 09:05 UTC, Frilock commented on gateway/src/main/resources/application.properties
> +#logging.level.org.apache.http=DEBUG
Давайте уберем закомментированный код

2022-10-31 09:05 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/server/booking/BookingRowMapper.java
> +@RequiredArgsConstructor
Лишняя аннотация, для чего она тут?

2022-10-31 09:05 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/server/comment/CommentRowMapper.java
> +@RequiredArgsConstructor
Лишняя аннотация

2022-10-31 09:05 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/server/item/ItemRepository.java
> +    List<Item> findAllByItemRequest_Id(Long itemRequestId);
Предлагаю и дальше camelCase использовать, можно _ убрать

2022-10-31 09:05 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/server/item/ItemRowMapper.java
> +@RequiredArgsConstructor
Лишняя аннотация

2022-10-31 09:05 UTC, Frilock commented on server/src/main/java/ru/practicum/shareit/server/user/UserRowMapper.java
> +@RequiredArgsConstructor
Лишняя аннотация...

2022-10-31 09:05 UTC, Frilock commented on server/src/test/java/ru/practicum/shareit/server/item/ItemControllerTest.java
> -    void getAllItemsTest() throws Exception {
А почему данный тест удалили?

2022-10-31 09:05 UTC, Frilock commented on server/src/test/java/ru/practicum/shareit/server/booking/BookingControllerTest.java
> -    void getAllBookingsByBookerIdTest() throws Exception {
А почему данные тесты удалили?

2022-10-31 20:42 UTC, nikolay-977 commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/BookingController.java
> +@Slf4j
убрал

2022-10-31 20:42 UTC, nikolay-977 commented on gateway/src/main/java/ru/practicum/shareit/gateway/booking/dto/BookingState.java
> +    WAITING;
исправил

2022-10-31 20:42 UTC, nikolay-977 commented on gateway/src/main/java/ru/practicum/shareit/gateway/client/BaseClient.java
> +    private <T> ResponseEntity<Object> makeAndSendRequest(HttpMethod method, String path, Long userId, @Nullable Map<String, Object> parameters, @Nullable T body) {
исправил

2022-10-31 20:42 UTC, nikolay-977 commented on server/src/main/java/ru/practicum/shareit/server/item/ItemRepository.java
> +    List<Item> findAllByItemRequest_Id(Long itemRequestId);
исправил

2022-10-31 20:42 UTC, nikolay-977 commented on server/src/main/java/ru/practicum/shareit/server/user/UserRowMapper.java
> +@RequiredArgsConstructor
исправил

2022-10-31 20:43 UTC, nikolay-977 commented on server/src/test/java/ru/practicum/shareit/server/item/ItemControllerTest.java
> -    void getAllItemsTest() throws Exception {
вернул

2022-10-31 20:43 UTC, nikolay-977 commented on server/src/test/java/ru/practicum/shareit/server/booking/BookingControllerTest.java
> -    void getAllBookingsByBookerIdTest() throws Exception {
вернул

2022-10-31 20:52 UTC, nikolay-977 commented on gateway/src/main/java/ru/practicum/shareit/gateway/client/BaseClient.java
> +            if (parameters != null) {
исправил

2022-10-31 20:54 UTC, nikolay-977 commented on gateway/src/main/java/ru/practicum/shareit/gateway/client/BaseClient.java
> +        if (response.getStatusCode().is2xxSuccessful()) {
Предполагается, что если сервер будет недоступен - должен вернуться 500-й код, или может быть по-другому?

2022-10-31 20:54 UTC, nikolay-977 commented on server/src/main/java/ru/practicum/shareit/server/item/ItemRowMapper.java
> +@RequiredArgsConstructor
исправил

2022-10-31 21:28 UTC, nikolay-977 commented
> Добрый день, оставил ряд комментариев к работе. Жду новую итерацию.

Добрый день, спасибо за ревью. Исправления внесены.

2022-11-01 18:08 UTC, Frilock approved these changes
Добрый вечер, работу принял

2022-11-01 18:34 UTC, merged